using System.Collections;
using System.Collections.Generic;
using Unity.Mathematics;
using Unity.VisualScripting;
using Unity.VisualScripting.FullSerializer;
using UnityEngine;
using UnityEngine.UI;

public class stageBoss_1 : MonoBehaviour

//ï¿½{ï¿½Xï¿½Í‘Sï¿½Ä‚Ìï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ÌƒXï¿½Nï¿½ï¿½ï¿½vï¿½gï¿½Åï¿½ï¿½sï¿½ï¿½ï¿½ï¿½
//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½AUIï¿½Íï¿½ï¿½ï¿½
{
    [SerializeField] float start_y_Pos = 3 , moveSpeed;
    [SerializeField] GameObject HP_slider , spell_bg;

    [SerializeField] GameObject[] phase_1_bullet;


    GameObject playerObj , bom , canvas , score , resObj ,bg ,gM;

    Text _text;
    public int hit_point = 1, kill_point = 10, now_score;

    Rigidbody2D rb;
    BoxCollider2D bc;
    Slider slider;
    public float HP = 200;

    bool isSpell = false , isPhase_1 = false , isPhase_2 = false;

    System.Random rnd;

    AudioSource _audio;
    soundMaster sm;
    public AudioClip audioClip , spellSe , damageSe ,spellEndSe;

    void Start()
    {
        _audio = GetComponent<AudioSource>();
        gM = GameObject.Find("GameMaster");
        sm = gM.GetComponent<soundMaster>();

        bc = GetComponent<BoxCollider2D>();
        bc.enabled = false;//ï¿½Åï¿½ï¿½Í–ï¿½ï¿½G

        rb = GetComponent<Rigidbody2D>();

        rnd = new System.Random();      // Randomï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ï¿½ï¿½ì¬

        playerObj = GameObject.Find("player");
        
        player_shot player_shot = playerObj.GetComponent<player_shot>();


        if (player_shot.my_power > player_shot.power_level * 2) HP *= 3;
        else if (player_shot.my_power > player_shot.power_level ) HP *= 2;

        bom = Instantiate(bom_obj);
        bom.SetActive(false);

        //scoreï¿½ÖŒW
        canvas = GameObject.Find("Canvas_2");
        score = canvas.transform.Find("score").gameObject;

        

        StartCoroutine(buttleStart());//ï¿½oï¿½ê•ï¿½ï¿½ï¿½Gï¿½ï¿½ï¿½ï¿½
    }

    bool stopd = false , isLoop = false;

    
    private void Update()
    {
        if(slider == null)return;
        if(slider.value <= (slider.maxValue / 10) * 3)//ï¿½ï¿½HPï¿½ï¿½ï¿½cï¿½ï¿½3ï¿½ï¿½ï¿½É‚È‚ï¿½ï¿½ï¿½ï¿½ï¿½
        {
            if (stopd == false && isPhase_1)
            { 
                StopAllCoroutines();
                stopd = true;
                StartCoroutine(spell_1());
            }
            else if (stopd == false && isPhase_2)
            {
                StopAllCoroutines();
                stopd = true;
                StartCoroutine(spell_2());
            }

        }
        if (_audio.isPlaying == false && isLoop == false)
        {
            isLoop = true;
            _audio.clip = audioClip;
            _audio.Play();
            _audio.loop = true;
        }
    }

    //ï¿½ï¿½eï¿½ï¿½ï¿½ï¿½

    //ï¿½ï¿½ï¿½ï¿½ï¿½Ìï¿½ï¿½lï¿½Í—vï¿½ï¿½ï¿½ï¿½
    float spell_damage = 0.5f;
    public List<GameObject> nextHP = new List<GameObject>();
    private void OnTriggerEnter2D(Collider2D collision)
    {
        if (collision.CompareTag("player_bullet"))
        {
            //sm.PlaySE(damageSe);
            Destroy(collision.gameObject);
            //score ï¿½Ì‘ï¿½ï¿½ï¿½
            _text = score.GetComponent<Text>();
            now_score = int.Parse(_text.text);

            now_score += hit_point;
            _text.text = now_score.ToString();

            if (isSpell) HP -= spell_damage;
            else HP--;//ï¿½ï¿½ï¿½ï¿½ï¿½Í•Ï‚ï¿½ï¿½È‚ï¿½



            if (isPhase_1) slider.value = HP - slider.maxValue;
            else if (isPhase_2) slider.value = HP;
            if (slider.value <= 0 && isPhase_1)
            {
                bom.SetActive(true);//ï¿½Sï¿½Gï¿½eï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
                Destroy(bg);
                sm.PlaySE(spellEndSe);
                StopAllCoroutines();//ï¿½Rï¿½ï¿½ï¿½[ï¿½`ï¿½ï¿½ï¿½ï¿½Sï¿½Ä’ï¿½~

                isPhase_1 = false;//ï¿½Aï¿½ï¿½ï¿½Ä‚Ñ‚ï¿½hï¿½~
                
                slider.value = slider.maxValue;

                stopd = false;
                isSpell = false;

                Image HP_0_image = nextHP[0].GetComponent<Image>();
                UnityEngine.Color c = HP_0_image.color;
                c = new Color(0.1509f, 0.1309f, 0.1217f);//ï¿½Fï¿½ï¿½ï¿½wï¿½ï¿½
                HP_0_image.color = c;//ï¿½Tï¿½ï¿½ï¿½ï¿½HPï¿½oï¿½[ï¿½ï¿½1ï¿½Âï¿½ï¿½É‚ï¿½ï¿½ï¿½

                bc.enabled = false;//ï¿½ï¿½ï¿½ï¿½ï¿½è”»ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½

                StartCoroutine(phase_2());
            }
            //ï¿½ï¿½ï¿½ï¿½ï¿½Éƒ{ï¿½Xï¿½ï¿½ï¿½ï¿½ï¿½jï¿½ï¿½ï¿½ê‚½ï¿½ï¿½ï¿½Ìï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
            else if(slider.value <= 0 && isPhase_2)
            {
                bom.SetActive(true);//ï¿½Sï¿½Gï¿½eï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
                Destroy (bg);
                player_bom pb = playerObj.GetComponent<player_bom>();
                pb.Invincible = true;

                StopAllCoroutines();//ï¿½Rï¿½ï¿½ï¿½[ï¿½`ï¿½ï¿½ï¿½ï¿½Sï¿½Ä’ï¿½~

                isPhase_2 = false;//ï¿½Aï¿½ï¿½ï¿½Ä‚Ñ‚ï¿½hï¿½~
                //stopd = false;
                resObj = GameObject.Find("GameMaster");
                StartCoroutine(resObj.GetComponent<Resurrection>().end(true));

                Destroy(_hp);
                gameObject.GetComponent<BoxCollider2D>().enabled = false;
                gameObject.GetComponent<SpriteRenderer>().enabled = false;
                
            }
        }
    }

    GameObject _hp;
    IEnumerator buttleStart()
    {
        //ï¿½ï¿½ï¿½É~ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½ï¿½ï¿½
        while (gameObject.transform.position.y > start_y_Pos)
        {
            Vector2 pos = gameObject.transform.position - new Vector3(0,moveSpeed,0);
            rb.MovePosition(pos);

            yield return null;
        }

        yield return new WaitForSeconds(2);


        _hp = Instantiate(HP_slider);//HPï¿½oï¿½[ï¿½ï¿½\ï¿½ï¿½

        int nextHP_count = 2;
        for (int i = 1; i <= nextHP_count; i++)//ï¿½ï¿½ï¿½ï¿½HPï¿½oï¿½[ï¿½ÌƒIï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ï¿½ï¿½æ“¾
        {
            nextHP.Add(_hp.transform.GetChild(i).gameObject);
        }
        //ï¿½ï¿½ï¿½ï¿½ï¿½Æ‚Åï¿½ï¿½ï¿½
        //nextHP[0].SetActive(false);

        slider = _hp.transform.Find("Slider").GetComponent<Slider>();//sliderï¿½ï¿½ï¿½æ“¾
        slider.maxValue = HP/2;
        slider.value = slider.maxValue;//HPï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½

        bc.enabled = true;//ï¿½ï¿½ï¿½ï¿½ï¿½è”»ï¿½ï¿½ï¿½ture


        isPhase_1 = true;
        StartCoroutine(phase_1());
    }

    int frame_1 = 0 , shotFrame = 158;

    IEnumerator phase_1()
    {
        float xPos , i_1=0 , add_i =0.01f ;

        
        StartCoroutine(circleShot());

        yield return new WaitForSeconds(2);

        StartCoroutine(eimShot_1());

        while (true)
        {
            xPos = math.sin(i_1);
            i_1 += add_i;

            Vector2 pos = new Vector3(xPos*2, gameObject.transform.position.y, 0);
            rb.MovePosition (pos);

            frame_1++;//ï¿½Ú“ï¿½ï¿½ï¿½ÉŒï¿½ï¿½Âï¿½ï¿½ï¿½
            if (frame_1 == shotFrame)yield return StartCoroutine(circleShot());
            if(frame_1 == shotFrame*2) StartCoroutine(circleShot());
            if(frame_1 == shotFrame * 3)yield return StartCoroutine(circleShot());
            if (frame_1 == shotFrame * 4)
            {
                StartCoroutine(circleShot());
                frame_1 = 0;//ï¿½ï¿½ï¿½É–ß‚ï¿½ï¿½ix=0ï¿½j
            }

            yield return null;  
        }
    }
    public List<Vector2> Raw_eimPos;
    IEnumerator eimShot_1()
    {
        while (true)
        {
            List<Vector2> clonePos = new List<Vector2>(Raw_eimPos);//ï¿½Rï¿½sï¿½[

            int rand_n = rnd.Next(clonePos.Count/2, clonePos.Count);
            for (int i = 0; i < rand_n; i++)
            {
                int rand_index = rnd.Next(0, clonePos.Count);//ï¿½Cï¿½ï¿½ï¿½fï¿½bï¿½Nï¿½Xï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½_ï¿½ï¿½ï¿½Éï¿½ï¿½ï¿½
                Instantiate(phase_1_bullet[1], clonePos[rand_index], Quaternion.identity);//ï¿½ï¿½ï¿½ï¿½ï¿½_ï¿½ï¿½ï¿½Èï¿½ï¿½Wï¿½Éï¿½ï¿½@ï¿½_ï¿½ï¿½ï¿½eï¿½ğ¶ï¿½
                clonePos.RemoveAt(rand_index);//ï¿½gï¿½pï¿½ï¿½ï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½fï¿½bï¿½Nï¿½Xï¿½ï¿½ï¿½íœ
                yield return new WaitForSeconds(1);
            }

            yield return new WaitForSeconds(2);
        }
    }
    
    IEnumerator circleShot()
    {

        int circleNum = 45;
        float addAngle = 4;

        float ms_1 = 0.05f, ms_2 = 0.1f;

        float _ = rnd.Next(0, 2);//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Èï¿½Aï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½

        if (_ == 0)
        {
            for (int i = 0; i < circleNum; i++)
            {
                Straight_move straight_Move = Instantiate(phase_1_bullet[0], gameObject.transform.position, Quaternion.Euler(0, 0, i * 8))
                    .GetComponent<Straight_move>();
                straight_Move.moveSpeed = ms_1;
            }
            yield return new WaitForSeconds(0.25f);

            for (int i = 0; i < circleNum; i++)
            {
                Straight_move straight_Move = Instantiate(phase_1_bullet[0], gameObject.transform.position, Quaternion.Euler(0, 0, i * 8 + addAngle))
                    .GetComponent<Straight_move>();
                straight_Move.moveSpeed = ms_2;
            }
            yield return new WaitForSeconds(3);
        }
        else
        {
            for (int i = 0; i < circleNum; i++)
            {
                Straight_move straight_Move = Instantiate(phase_1_bullet[0], gameObject.transform.position, Quaternion.Euler(0, 0, i * 8 + addAngle))
                    .GetComponent<Straight_move>();
                straight_Move.moveSpeed = ms_1;
            }
            yield return new WaitForSeconds(0.25f);

            for (int i = 0; i < circleNum; i++)
            {
                Straight_move straight_Move = Instantiate(phase_1_bullet[0], gameObject.transform.position, Quaternion.Euler(0, 0, i * 8))
                    .GetComponent<Straight_move>();
                straight_Move.moveSpeed = ms_2;
            }
            yield return new WaitForSeconds(3);
        }
    }

    Vector3 spell_myPos = new Vector3(0, 3, 0);
    float spell_1_moveSpeed = 0.01f;

    public GameObject eim_bullet ,eim_bullet_2, wave_bullet;

    IEnumerator spell_1()
    {
        yield return StartCoroutine(spell_Anime(1));//ï¿½ï¿½ï¿½\ï¿½bï¿½hï¿½Ì–ï¿½ï¿½Oï¿½Éispell_1ï¿½jï¿½ï¿½1ï¿½É‚ï¿½ï¿½í‚¹ï¿½ï¿½
        //ï¿½{ï¿½ï¿½ï¿½ï¿½0ï¿½Ì•ï¿½ï¿½ï¿½ï¿½Dï¿½Ü‚ï¿½ï¿½ï¿½
        
        //ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Xï¿½yï¿½ï¿½ï¿½Jï¿½[ï¿½hï¿½Ì’eï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        while (true)
        {
            Instantiate(wave_bullet, transform.position, quaternion.identity);
            Instantiate(wave_bullet, transform.position, quaternion.identity).GetComponent<waveBullet>().isMinus = true;

            Instantiate(eim_bullet, transform.position, quaternion.identity);
            Instantiate(eim_bullet, transform.position, quaternion.identity).GetComponent<big_eim>().minus = true;

            //sm.PlaySE(beepSe);
            yield return new WaitForSeconds(4);

            Instantiate(eim_bullet_2, transform.position, quaternion.identity);
            Instantiate(eim_bullet_2, transform.position, quaternion.identity).GetComponent<big_eim>().minus = true;
            yield return new WaitForSeconds(6);
        }

    }
    public GameObject[] enemy_image;
    public GameObject bom_obj ;
    IEnumerator spell_Anime(int image_num)
    {
        bc.enabled = false;//ï¿½ï¿½ï¿½ï¿½ï¿½è”»ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        isSpell = true;

        sm.PlaySE(spellSe);
        bg = Instantiate(spell_bg, new Vector3(0, 0, 0), Quaternion.identity);
        
        yield return null;
        bom.SetActive(true);

        Vector3 velocity = spell_myPos - gameObject.transform.position;//ï¿½xï¿½Nï¿½gï¿½ï¿½ï¿½ï¿½ï¿½vï¿½Z
        bool right = false;
        if (velocity.x > 0) right = true;//ï¿½iï¿½sï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Eï¿½iXï¿½ï¿½ï¿½ï¿½ï¿½Ìƒxï¿½Nï¿½gï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ì’lï¿½jï¿½Ìê‡ï¿½ï¿½true

        GameObject Animetion_obj = Instantiate(enemy_image[image_num]);//UIï¿½Aï¿½jï¿½ï¿½ï¿½[ï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Äï¿½ï¿½iï¿½Xï¿½yï¿½ï¿½ï¿½Jï¿½[ï¿½hï¿½ï¿½ï¿½j

        //ï¿½ï¿½Ê’uï¿½Ü‚ÅˆÚ“ï¿½
        while (gameObject.transform.position != spell_myPos)
        {


            Vector3 movePos = gameObject.transform.position + velocity * spell_1_moveSpeed;

            if (right && movePos.x > 0) movePos = spell_myPos;//ï¿½ï¿½ï¿½ï¿½
            if (right == false && movePos.x < 0) movePos = spell_myPos;//ï¿½ï¿½ï¿½ï¿½

            rb.MovePosition(movePos);

            yield return null;
        }

        spell_animetion sa = Animetion_obj.transform.Find("enemy_image").gameObject.GetComponent<spell_animetion>();
        //UIï¿½Aï¿½jï¿½ï¿½ï¿½[ï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Äï¿½ï¿½ï¿½ï¿½ê‚½ï¿½ï¿½Eï¿½o
        while (sa.finish == false)
        {
            sa = Animetion_obj.transform.GetChild(0).gameObject.GetComponent<spell_animetion>();
            yield return null;
        }

        Destroy(Animetion_obj);
        bom.SetActive(false);

        bc.enabled = true;//ï¿½ï¿½ï¿½ï¿½ï¿½è”»ï¿½ï¿½ğ•œŠï¿½

    }
    public GameObject[] phase2_bullets;
    IEnumerator phase_2()
    {
        yield return new WaitForSeconds(3);

        bc.enabled = true;//ï¿½ï¿½ï¿½ï¿½ï¿½è”»ï¿½ï¿½ï¿½ï¿½ï¿½

        bom.SetActive(false);
        isPhase_2 = true;

        float add_i=0.0001f;
        float sum_vect = 0;
        Vector3 goale_pos = new Vector3(-4, -1.5f, 0);
        //Vector3 goale_vect = transform.position - goale_pos;
        while (transform.position != new Vector3(-4, 1.5f, 0))
        {
            
            rb.MovePosition(gameObject.transform.position + goale_pos * sum_vect);

            if (transform.position.x < -4) gameObject.transform.position = new Vector3(-4 , 1.5f,0);
            else sum_vect += add_i;
            yield return null;

        }

        goale_pos = new Vector3(4, 0.75f, 0);
        sum_vect = 0;

        add_i = 0.0001f;
        int i = 0;
        yield return new WaitForSeconds(1);

        System.Random random = new System.Random();
        int loop_count = 3;

        while (transform.position != new Vector3(4, 3f, 0))
        {

            rb.MovePosition(gameObject.transform.position + goale_pos * sum_vect);

            if (transform.position.x > 4) gameObject.transform.position = new Vector3(4, 3, 0);
            else sum_vect += add_i;

            int frame = 10;

            i++;
            if (i % frame == 0)
            {
                for (int j = 0; j < loop_count; j++)
                {
                    int ran_int = random.Next(-25, 25);
                    int ran_speed = random.Next(3, 10);

                    GameObject g_bullet = Instantiate(phase2_bullets[1], transform.position, Quaternion.Euler(0, 0, (i / frame) + ran_int));
                    g_bullet.GetComponent<Straight_move>().moveSpeed = ran_speed * 0.01f;
                    SpriteRenderer sr = g_bullet.GetComponent<SpriteRenderer>();
                    switch (UnityEngine.Random.Range(0, 7))
                    {
                        case 0:
                            sr.color = Color.white
                                ; break;
                        case 1:
                            sr.color = Color.red
                                ; break;
                        case 2:
                            //sr.color = Color.blue
                                ; break;
                        case 3:
                            sr.color = Color.green
                                ; break;
                        case 4:
                            sr.color = Color.cyan
                                ; break;
                        case 5:
                            sr.color = Color.magenta
                                ; break;
                        case 6:
                            sr.color = Color.yellow
                                ; break;
                    }//ï¿½Fï¿½ï¿½Ï‚ï¿½ï¿½ï¿½
                }
            }
            yield return null;

        }
        yield return new WaitForSeconds(1);

        goale_pos = new Vector3(-1, 0, 0);
        sum_vect = 0;

        add_i = 0.0001f;

        bool shoted = false;
        while (transform.position != new Vector3(0, 3f, 0))
        {

            rb.MovePosition(gameObject.transform.position + goale_pos * sum_vect);

            if (transform.position.x <= 2 && shoted == false)
            {
                shoted = true;
                Instantiate(phase2_bullets[2], gameObject.transform.position, Quaternion.identity);//ï¿½ï¿½ï¿½@ï¿½_ï¿½ï¿½ï¿½ÌŠgï¿½Uï¿½e
                                                                                                   //ï¿½gï¿½ï¿½ï¿½ï¿½EXï¿½Ì’ï¿½ï¿½{ï¿½Xï¿½|ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½É—dï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½Aï¿½ï¿½ ï¿½ï¿½ï¿½ê”­
            }
            if (transform.position.x < 0) gameObject.transform.position = new Vector3(0, 3, 0);
            else sum_vect += add_i;

            yield return null;

        }
        int gravity_int = 50;

        for(int ii = 0; ii < gravity_int; ii++)
        {
           SpriteRenderer sr = Instantiate(phase2_bullets[3] , transform.position ,Quaternion.identity).GetComponent<SpriteRenderer>();
            switch(UnityEngine.Random.Range(0, 7))
            {
                case 0:
                    sr.color = Color.white
                        ;break;
                case 1:
                    sr.color = Color.red
                        ; break;
                case 2:
                    //sr.color = Color.blue
                        ; break;
                case 3:
                    sr.color = Color.green
                        ; break;
                case 4:
                    sr.color = Color.cyan
                        ; break;
                case 5:
                    sr.color = Color.magenta
                        ; break;
                case 6:
                    sr.color = Color.yellow
                        ; break;
            }//ï¿½Fï¿½ï¿½Ï‚ï¿½ï¿½ï¿½

            yield return null; yield return null;//2frameï¿½Ò‚ï¿½
        }
        StartCoroutine(phase_2());//ï¿½Jï¿½ï¿½Ô‚ï¿½
    }
    [SerializeField] Vector2 wall_bullet_Pos1, wall_bullet_Pos2;
    IEnumerator spell_2()
    {
        yield return StartCoroutine(spell_Anime(2));
        StartCoroutine(wallShot());

        float i = 0, add_i = 0.01f;
        int shotCount = 0 , interval = 12;
        while (true)
        {
            if (shotCount <= interval)
            {
                float angle = math.sin(i);
                i += add_i;
                Instantiate(phase2_bullets[5], transform.position, Quaternion.Euler(0, 0, angle));

                for (int t = 0; t < 10; t++)//10ï¿½tï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½Ò‹@
                    yield return null;
                shotCount++;
            }
            else
            {
                shotCount = 0;
                yield return new WaitForSeconds(0.5f);
            }
        }
        
    }
    IEnumerator wallShot()
    {
        int wall_n = 4;
        while (true) 
        {
            for (int i = 0; i < wall_n; i++)
            {
                Instantiate(phase2_bullets[4], wall_bullet_Pos1, Quaternion.identity);
                Instantiate(phase2_bullets[4], wall_bullet_Pos2, Quaternion.Euler(0, 0, 180));
                //ï¿½}ï¿½Cï¿½iï¿½Xï¿½ï¿½ï¿½Wï¿½Éoï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
                Instantiate(phase2_bullets[4], -wall_bullet_Pos2, Quaternion.identity);
                Instantiate(phase2_bullets[4], -wall_bullet_Pos1, Quaternion.Euler(0, 0, 180));

            }
            yield return new WaitForSeconds(1f);
        }
    }
    




}

